name: phonepe_flutter
description: >
  Flutter helper to launch a PhonePe checkout flow, return via deep link,
  and expose a simple status for in-app payments with sandbox/production configs.
version: 1.1.0

repository: https://github.com/goutam2597/phonepe.git
issue_tracker: https://github.com/goutam2597/phonepe/issues
topics:
  - payments
  - checkout
  - phonepe
  - upi

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  http: ^1.5.0
  crypto: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # declare assets here if needed
